### ISSUE TITLE
Download only package changes

### ISSUE THREAD

**Issue by alextrical** [dzervas/fusion360-streamer#4]
Really nice looking application so far, thank you for your hard work. I'm currently trying to get my head around how to make it download and extract. (with the goal of using it in a wine script)

Would it be possible to eventually get the the system to skip existing packages, something on par with 'No Clober' from Wget to speed up the update process?

**Comment by dzervas** [comment]
It does skip re-downloading packages but not JSONs.

I guess it's not very clear from the README (my bad) but the whole process is:

1. Get the `full.json` which describes all the packages for the app and the sub-applications
2. Get the json files of the packages
3. Do the same for all the sub-applications
4. Download all the packages. If the package with the same name exists and the sha1 sum matches (the name of each package is its own sha1 hash) skip it
5. Do the same for all the sub-applications
6. Extract all the packages (here everything gets re-extracted as we can't be sure that everything got extracted in a previous run correctly)
7. Do the same for all the sub-applications

Have you seen a different behavior?

**Comment by dzervas** [comment]
huh, something changed:

```
$ sha1sum baf58980ef576109b2022dc95869f9c0240b3a0d.tar.xz
9fffff5e181d797962936dea742c5fe29b0adefc  baf58980ef576109b2022dc95869f9c0240b3a0d.tar.xz
```

the hash algorithm seems different
